services:
    db-notessvc:
      image: postgres:16
      environment:
        POSTGRES_PASSWORD: bear
        POSTGRES_DB: notedb
      ports:
        - "5432:5432"
      volumes:
        - "pgdata_notessvc:/var/lib/postgresql/data"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d notedb"]
        interval: 5s
        timeout: 3s
        retries: 5

    db-gateway:
      image: postgres:16
      environment:
        POSTGRES_PASSWORD: bear
        POSTGRES_DB: gatewaydb
      ports:
        - "5433:5432"
      volumes:
        - "pgdata_gateway:/var/lib/postgresql/data"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d gatewaydb"]
        interval: 5s
        timeout: 3s
        retries: 5

        
    migrate-notessvc:
      image: ghcr.io/kukymbr/goose-docker:3.24.3
      depends_on:
        db-notessvc:
          condition: service_healthy
      volumes:
        - ./migrations/notes-svc:/migrations:ro
      entrypoint: ["goose", "-dir", "/migrations", "up"]
      environment:
        GOOSE_DRIVER: postgres
        GOOSE_DBSTRING: postgres://postgres:bear@db-notessvc:5432/notedb?sslmode=disable
        GOOSE_MIGRATION_DIR: /migrations

    migrate-gateway:
      image: ghcr.io/kukymbr/goose-docker:3.24.3
      depends_on:
        db-gateway:
          condition: service_healthy
      volumes:
        - ./migrations/gateway:/migrations:ro
      entrypoint: ["goose", "-dir", "/migrations", "up"]
      environment:
        GOOSE_DRIVER: postgres
        GOOSE_DBSTRING: postgres://postgres:bear@db-gateway:5432/gatewaydb?sslmode=disable
        GOOSE_MIGRATION_DIR: /migrations
        
    notes:
      build: 
        context: .
        dockerfile: cmd/notes-svc/Dockerfile
      image: notesapp
      depends_on:
        migrate-notessvc:
          condition: service_completed_successfully
      ports:
        - "5681:5681"
        - "5685:5685"
      volumes:
        -  ./config/notes-svc/config.yaml:/app/configs/config.yaml:ro
      healthcheck:
         test: ["CMD-SHELL", "wget -qO- --spider http://localhost:5685/health || exit 1"]
         interval: 5s
         timeout: 3s
         retries: 10
      

    gateway:
      build:
        context: .
        dockerfile: cmd/gateway/Dockerfile
      depends_on:
        notes:
          condition: service_healthy
        migrate-gateway:
          condition: service_completed_successfully
      ports:
        - "5680:5680"
      volumes:
        - ./config/gateway/config.yaml:/app/configs/config.yaml:ro
      healthcheck:
         test: ["CMD-SHELL", "wget -qO- --spider http://localhost:5680/health || exit 1"]
         interval: 5s
         timeout: 3s
         retries: 10
      secrets:
        - source: jwt_secret
          target: /run/secrets/jwt_secret
    prometheus:
      image: prom/prometheus
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      ports:
        - "9090:9090"

    swagger-ui:
      image: docker.swagger.io/swaggerapi/swagger-ui
      ports:
        - "5682:8080"
      volumes:
        - ./api/openapi/notes.yaml:/spec/notes.yaml:ro
      environment:
        SWAGGER_JSON: /spec/notes.yaml
        WITH_CREDENTIALS: "true"
        
secrets:
  jwt_secret:
    file: ./secrets/jwt_secret
  

volumes:
  pgdata_notessvc:
  pgdata_gateway:
