// Code generated by MockGen. DO NOT EDIT.
// Source: internal/gateway/service/auth/authSVC.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	authsvc "notes/internal/gateway/service/auth"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIAuthSVC is a mock of IAuthSVC interface.
type MockIAuthSVC struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthSVCMockRecorder
}

// MockIAuthSVCMockRecorder is the mock recorder for MockIAuthSVC.
type MockIAuthSVCMockRecorder struct {
	mock *MockIAuthSVC
}

// NewMockIAuthSVC creates a new mock instance.
func NewMockIAuthSVC(ctrl *gomock.Controller) *MockIAuthSVC {
	mock := &MockIAuthSVC{ctrl: ctrl}
	mock.recorder = &MockIAuthSVCMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthSVC) EXPECT() *MockIAuthSVCMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockIAuthSVC) Login(ctx context.Context, req authsvc.LoginReq) (authsvc.AuthResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(authsvc.AuthResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockIAuthSVCMockRecorder) Login(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockIAuthSVC)(nil).Login), ctx, req)
}

// Refresh mocks base method.
func (m *MockIAuthSVC) Refresh(ctx context.Context, refresh string) (authsvc.AuthResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, refresh)
	ret0, _ := ret[0].(authsvc.AuthResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockIAuthSVCMockRecorder) Refresh(ctx, refresh interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockIAuthSVC)(nil).Refresh), ctx, refresh)
}

// Signup mocks base method.
func (m *MockIAuthSVC) Signup(ctx context.Context, req authsvc.SignUpReq) (authsvc.AuthResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signup", ctx, req)
	ret0, _ := ret[0].(authsvc.AuthResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signup indicates an expected call of Signup.
func (mr *MockIAuthSVCMockRecorder) Signup(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signup", reflect.TypeOf((*MockIAuthSVC)(nil).Signup), ctx, req)
}
